package sk.vracon.sqlcomments.maven.generate;

import java.sql.Array;
import java.sql.Blob;
import java.util.Date;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Query result class for statement blobMappings.
 * <p>
 * Generated by SQLComments.
 */
public class BlobMappings {

    private Array array;
    private Long bigint;
    private byte[] binary;
    private Blob blob;
    private Boolean boolean_;
    private String char_;
    private String clob;
    private Date date;
    private BigDecimal decimal;
    private Double double_;
    private Double float_;
    private Integer integer;
    private String intervalDs;
    private String intervalYm;
    private BigDecimal numeric;
    private Double real;
    private Integer smallint;
    private Date time;
    private Date timestamp;
    private OffsetDateTime timestampTz;
    private Integer tinyint;
    private byte[] uuid;
    private byte[] varbinary;
    private String varchar;
    private String varcharIgnorecase;

    public Array getArray() {
        return array;
    }

    public void setArray(Array newValue) {
        this.array = newValue;
    }

    public Long getBigint() {
        return bigint;
    }

    public void setBigint(Long newValue) {
        this.bigint = newValue;
    }

    public byte[] getBinary() {
        return binary;
    }

    public void setBinary(byte[] newValue) {
        this.binary = newValue;
    }

    public Blob getBlob() {
        return blob;
    }

    public void setBlob(Blob newValue) {
        this.blob = newValue;
    }

    public Boolean getBoolean_() {
        return boolean_;
    }

    public void setBoolean_(Boolean newValue) {
        this.boolean_ = newValue;
    }

    public String getChar_() {
        return char_;
    }

    public void setChar_(String newValue) {
        this.char_ = newValue;
    }

    public String getClob() {
        return clob;
    }

    public void setClob(String newValue) {
        this.clob = newValue;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date newValue) {
        this.date = newValue;
    }

    public BigDecimal getDecimal() {
        return decimal;
    }

    public void setDecimal(BigDecimal newValue) {
        this.decimal = newValue;
    }

    public Double getDouble_() {
        return double_;
    }

    public void setDouble_(Double newValue) {
        this.double_ = newValue;
    }

    public Double getFloat_() {
        return float_;
    }

    public void setFloat_(Double newValue) {
        this.float_ = newValue;
    }

    public Integer getInteger() {
        return integer;
    }

    public void setInteger(Integer newValue) {
        this.integer = newValue;
    }

    public String getIntervalDs() {
        return intervalDs;
    }

    public void setIntervalDs(String newValue) {
        this.intervalDs = newValue;
    }

    public String getIntervalYm() {
        return intervalYm;
    }

    public void setIntervalYm(String newValue) {
        this.intervalYm = newValue;
    }

    public BigDecimal getNumeric() {
        return numeric;
    }

    public void setNumeric(BigDecimal newValue) {
        this.numeric = newValue;
    }

    public Double getReal() {
        return real;
    }

    public void setReal(Double newValue) {
        this.real = newValue;
    }

    public Integer getSmallint() {
        return smallint;
    }

    public void setSmallint(Integer newValue) {
        this.smallint = newValue;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date newValue) {
        this.time = newValue;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date newValue) {
        this.timestamp = newValue;
    }

    public OffsetDateTime getTimestampTz() {
        return timestampTz;
    }

    public void setTimestampTz(OffsetDateTime newValue) {
        this.timestampTz = newValue;
    }

    public Integer getTinyint() {
        return tinyint;
    }

    public void setTinyint(Integer newValue) {
        this.tinyint = newValue;
    }

    public byte[] getUuid() {
        return uuid;
    }

    public void setUuid(byte[] newValue) {
        this.uuid = newValue;
    }

    public byte[] getVarbinary() {
        return varbinary;
    }

    public void setVarbinary(byte[] newValue) {
        this.varbinary = newValue;
    }

    public String getVarchar() {
        return varchar;
    }

    public void setVarchar(String newValue) {
        this.varchar = newValue;
    }

    public String getVarcharIgnorecase() {
        return varcharIgnorecase;
    }

    public void setVarcharIgnorecase(String newValue) {
        this.varcharIgnorecase = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("BlobMappings [array=");
        builder.append(array);
        builder.append(", bigint=");
        builder.append(bigint);
        builder.append(", binary=");
        builder.append(binary);
        builder.append(", blob=");
        builder.append(blob);
        builder.append(", boolean_=");
        builder.append(boolean_);
        builder.append(", char_=");
        builder.append(char_);
        builder.append(", clob=");
        builder.append(clob);
        builder.append(", date=");
        builder.append(date);
        builder.append(", decimal=");
        builder.append(decimal);
        builder.append(", double_=");
        builder.append(double_);
        builder.append(", float_=");
        builder.append(float_);
        builder.append(", integer=");
        builder.append(integer);
        builder.append(", intervalDs=");
        builder.append(intervalDs);
        builder.append(", intervalYm=");
        builder.append(intervalYm);
        builder.append(", numeric=");
        builder.append(numeric);
        builder.append(", real=");
        builder.append(real);
        builder.append(", smallint=");
        builder.append(smallint);
        builder.append(", time=");
        builder.append(time);
        builder.append(", timestamp=");
        builder.append(timestamp);
        builder.append(", timestampTz=");
        builder.append(timestampTz);
        builder.append(", tinyint=");
        builder.append(tinyint);
        builder.append(", uuid=");
        builder.append(uuid);
        builder.append(", varbinary=");
        builder.append(varbinary);
        builder.append(", varchar=");
        builder.append(varchar);
        builder.append(", varcharIgnorecase=");
        builder.append(varcharIgnorecase);
        builder.append("]");
        return builder.toString();
    }
    
}