package sk.vracon.sqlcomments.maven.generate;

import java.util.Date;
import java.util.Objects;

/**
 * Query result class for statement defaultResult.
 * <p>
 * Generated by SQLComments.
 */
public class DefaultResult {

    private Integer empno;
    private Date enddate;
    private Integer projid;
    private Date startdate;

    public Integer getEmpno() {
        return empno;
    }

    public void setEmpno(Integer newValue) {
        this.empno = newValue;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date newValue) {
        this.enddate = newValue;
    }

    public Integer getProjid() {
        return projid;
    }

    public void setProjid(Integer newValue) {
        this.projid = newValue;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date newValue) {
        this.startdate = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("DefaultResult [empno=");
        builder.append(empno);
        builder.append(", enddate=");
        builder.append(enddate);
        builder.append(", projid=");
        builder.append(projid);
        builder.append(", startdate=");
        builder.append(startdate);
        builder.append("]");
        return builder.toString();
    }
    
}