package sk.vracon.sqlcomments.maven.generate;

import java.util.Objects;

/**
 * Query result class for statement fullFeatured1.
 * <p>
 * Generated by SQLComments.
 */
public class FullFeatured1 {

    private Integer deptno;
    private String dname;
    private String employeename;
    private Integer empno;

    public Integer getDeptno() {
        return deptno;
    }

    public void setDeptno(Integer newValue) {
        this.deptno = newValue;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String newValue) {
        this.dname = newValue;
    }

    public String getEmployeename() {
        return employeename;
    }

    public void setEmployeename(String newValue) {
        this.employeename = newValue;
    }

    public Integer getEmpno() {
        return empno;
    }

    public void setEmpno(Integer newValue) {
        this.empno = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("FullFeatured1 [deptno=");
        builder.append(deptno);
        builder.append(", dname=");
        builder.append(dname);
        builder.append(", employeename=");
        builder.append(employeename);
        builder.append(", empno=");
        builder.append(empno);
        builder.append("]");
        return builder.toString();
    }
    
}