package sk.vracon.sqlcomments.maven.generate;

import java.util.Objects;

/**
 * Query result class for statement multipleAsterixes.
 * <p>
 * Generated by SQLComments.
 */
public class MultipleAsterixes {

    private Integer deptno;
    private String dname;
    private String ename;
    private String loc;

    public Integer getDeptno() {
        return deptno;
    }

    public void setDeptno(Integer newValue) {
        this.deptno = newValue;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String newValue) {
        this.dname = newValue;
    }

    public String getEname() {
        return ename;
    }

    public void setEname(String newValue) {
        this.ename = newValue;
    }

    public String getLoc() {
        return loc;
    }

    public void setLoc(String newValue) {
        this.loc = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("MultipleAsterixes [deptno=");
        builder.append(deptno);
        builder.append(", dname=");
        builder.append(dname);
        builder.append(", ename=");
        builder.append(ename);
        builder.append(", loc=");
        builder.append(loc);
        builder.append("]");
        return builder.toString();
    }
    
}