package sk.vracon.sqlcomments.maven.generate;

import java.util.Objects;

/**
 * Query result class for statement selectWithPlaceholder.
 * <p>
 * Generated by SQLComments.
 */
public class PlaceholderInsideInClause {

    private Integer deptno;
    private String dname;

    public Integer getDeptno() {
        return deptno;
    }

    public void setDeptno(Integer newValue) {
        this.deptno = newValue;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String newValue) {
        this.dname = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("PlaceholderInsideInClause [deptno=");
        builder.append(deptno);
        builder.append(", dname=");
        builder.append(dname);
        builder.append("]");
        return builder.toString();
    }
    
}