package sk.vracon.sqlcomments.maven.domain.Oracle;

import java.sql.Blob;
import java.util.Date;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.Period;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Datatypes {

    private Double bDouble;
    private Float bFloat;
    private Blob bfile;
    private Blob blob;
    private String charVar;
    private String char_;
    private String character;
    private String characterVar;
    private String clob;
    private Float dPrecision;
    private Date date;
    private BigDecimal dec;
    private BigDecimal decimal;
    private Float float_;
    private BigDecimal int_;
    private BigDecimal integer;
    private Duration intervalDay;
    private Period intervalYear;
    private String long_;
    private String nationalChar;
    private String nationalCharVar;
    private String nationalCharacter;
    private String nationalCharacterVarying;
    private String nchar;
    private String ncharVary;
    private String nclob;
    private BigDecimal number;
    private BigDecimal numeric;
    private byte[] raw;
    private Float real;
    private String rowid;
    private BigDecimal smallInt;
    private Date timestamp;
    private String urowid;
    private String varChar2;
    private String varchar;

    public Double getBDouble() {
        return bDouble;
    }

    public void setBDouble(Double newValue) {
        this.bDouble = newValue;
    }

    public Float getBFloat() {
        return bFloat;
    }

    public void setBFloat(Float newValue) {
        this.bFloat = newValue;
    }

    public Blob getBfile() {
        return bfile;
    }

    public void setBfile(Blob newValue) {
        this.bfile = newValue;
    }

    public Blob getBlob() {
        return blob;
    }

    public void setBlob(Blob newValue) {
        this.blob = newValue;
    }

    public String getCharVar() {
        return charVar;
    }

    public void setCharVar(String newValue) {
        this.charVar = newValue;
    }

    public String getChar_() {
        return char_;
    }

    public void setChar_(String newValue) {
        this.char_ = newValue;
    }

    public String getCharacter() {
        return character;
    }

    public void setCharacter(String newValue) {
        this.character = newValue;
    }

    public String getCharacterVar() {
        return characterVar;
    }

    public void setCharacterVar(String newValue) {
        this.characterVar = newValue;
    }

    public String getClob() {
        return clob;
    }

    public void setClob(String newValue) {
        this.clob = newValue;
    }

    public Float getDPrecision() {
        return dPrecision;
    }

    public void setDPrecision(Float newValue) {
        this.dPrecision = newValue;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date newValue) {
        this.date = newValue;
    }

    public BigDecimal getDec() {
        return dec;
    }

    public void setDec(BigDecimal newValue) {
        this.dec = newValue;
    }

    public BigDecimal getDecimal() {
        return decimal;
    }

    public void setDecimal(BigDecimal newValue) {
        this.decimal = newValue;
    }

    public Float getFloat_() {
        return float_;
    }

    public void setFloat_(Float newValue) {
        this.float_ = newValue;
    }

    public BigDecimal getInt_() {
        return int_;
    }

    public void setInt_(BigDecimal newValue) {
        this.int_ = newValue;
    }

    public BigDecimal getInteger() {
        return integer;
    }

    public void setInteger(BigDecimal newValue) {
        this.integer = newValue;
    }

    public Duration getIntervalDay() {
        return intervalDay;
    }

    public void setIntervalDay(Duration newValue) {
        this.intervalDay = newValue;
    }

    public Period getIntervalYear() {
        return intervalYear;
    }

    public void setIntervalYear(Period newValue) {
        this.intervalYear = newValue;
    }

    public String getLong_() {
        return long_;
    }

    public void setLong_(String newValue) {
        this.long_ = newValue;
    }

    public String getNationalChar() {
        return nationalChar;
    }

    public void setNationalChar(String newValue) {
        this.nationalChar = newValue;
    }

    public String getNationalCharVar() {
        return nationalCharVar;
    }

    public void setNationalCharVar(String newValue) {
        this.nationalCharVar = newValue;
    }

    public String getNationalCharacter() {
        return nationalCharacter;
    }

    public void setNationalCharacter(String newValue) {
        this.nationalCharacter = newValue;
    }

    public String getNationalCharacterVarying() {
        return nationalCharacterVarying;
    }

    public void setNationalCharacterVarying(String newValue) {
        this.nationalCharacterVarying = newValue;
    }

    public String getNchar() {
        return nchar;
    }

    public void setNchar(String newValue) {
        this.nchar = newValue;
    }

    public String getNcharVary() {
        return ncharVary;
    }

    public void setNcharVary(String newValue) {
        this.ncharVary = newValue;
    }

    public String getNclob() {
        return nclob;
    }

    public void setNclob(String newValue) {
        this.nclob = newValue;
    }

    public BigDecimal getNumber() {
        return number;
    }

    public void setNumber(BigDecimal newValue) {
        this.number = newValue;
    }

    public BigDecimal getNumeric() {
        return numeric;
    }

    public void setNumeric(BigDecimal newValue) {
        this.numeric = newValue;
    }

    public byte[] getRaw() {
        return raw;
    }

    public void setRaw(byte[] newValue) {
        this.raw = newValue;
    }

    public Float getReal() {
        return real;
    }

    public void setReal(Float newValue) {
        this.real = newValue;
    }

    public String getRowid() {
        return rowid;
    }

    public void setRowid(String newValue) {
        this.rowid = newValue;
    }

    public BigDecimal getSmallInt() {
        return smallInt;
    }

    public void setSmallInt(BigDecimal newValue) {
        this.smallInt = newValue;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date newValue) {
        this.timestamp = newValue;
    }

    public String getUrowid() {
        return urowid;
    }

    public void setUrowid(String newValue) {
        this.urowid = newValue;
    }

    public String getVarChar2() {
        return varChar2;
    }

    public void setVarChar2(String newValue) {
        this.varChar2 = newValue;
    }

    public String getVarchar() {
        return varchar;
    }

    public void setVarchar(String newValue) {
        this.varchar = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Datatypes [bDouble=");
        builder.append(bDouble);
        builder.append(", bFloat=");
        builder.append(bFloat);
        builder.append(", bfile=");
        builder.append(bfile);
        builder.append(", blob=");
        builder.append(blob);
        builder.append(", charVar=");
        builder.append(charVar);
        builder.append(", char_=");
        builder.append(char_);
        builder.append(", character=");
        builder.append(character);
        builder.append(", characterVar=");
        builder.append(characterVar);
        builder.append(", clob=");
        builder.append(clob);
        builder.append(", dPrecision=");
        builder.append(dPrecision);
        builder.append(", date=");
        builder.append(date);
        builder.append(", dec=");
        builder.append(dec);
        builder.append(", decimal=");
        builder.append(decimal);
        builder.append(", float_=");
        builder.append(float_);
        builder.append(", int_=");
        builder.append(int_);
        builder.append(", integer=");
        builder.append(integer);
        builder.append(", intervalDay=");
        builder.append(intervalDay);
        builder.append(", intervalYear=");
        builder.append(intervalYear);
        builder.append(", long_=");
        builder.append(long_);
        builder.append(", nationalChar=");
        builder.append(nationalChar);
        builder.append(", nationalCharVar=");
        builder.append(nationalCharVar);
        builder.append(", nationalCharacter=");
        builder.append(nationalCharacter);
        builder.append(", nationalCharacterVarying=");
        builder.append(nationalCharacterVarying);
        builder.append(", nchar=");
        builder.append(nchar);
        builder.append(", ncharVary=");
        builder.append(ncharVary);
        builder.append(", nclob=");
        builder.append(nclob);
        builder.append(", number=");
        builder.append(number);
        builder.append(", numeric=");
        builder.append(numeric);
        builder.append(", raw=");
        builder.append(raw);
        builder.append(", real=");
        builder.append(real);
        builder.append(", rowid=");
        builder.append(rowid);
        builder.append(", smallInt=");
        builder.append(smallInt);
        builder.append(", timestamp=");
        builder.append(timestamp);
        builder.append(", urowid=");
        builder.append(urowid);
        builder.append(", varChar2=");
        builder.append(varChar2);
        builder.append(", varchar=");
        builder.append(varchar);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Datatypes other = (Datatypes) obj;
        if (!Objects.equals(int_, other.int_)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((int_ == null) ? 0 : int_.hashCode());
        return result;
    }
}