package sk.vracon.sqlcomments.maven.domain.Oracle;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Project implements sk.vracon.sqlcomments.maven.IDomain {

    private BigDecimal empno;
    private Date enddate;
    private BigDecimal projid;
    private Date startdate;

    public BigDecimal getEmpno() {
        return empno;
    }

    public void setEmpno(BigDecimal newValue) {
        this.empno = newValue;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date newValue) {
        this.enddate = newValue;
    }

    public BigDecimal getProjid() {
        return projid;
    }

    public void setProjid(BigDecimal newValue) {
        this.projid = newValue;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date newValue) {
        this.startdate = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Project [empno=");
        builder.append(empno);
        builder.append(", enddate=");
        builder.append(enddate);
        builder.append(", projid=");
        builder.append(projid);
        builder.append(", startdate=");
        builder.append(startdate);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Project other = (Project) obj;
        if (!Objects.equals(projid, other.projid)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((projid == null) ? 0 : projid.hashCode());
        return result;
    }
}