<#if packageName?has_content>
package ${packageName};
</#if>

<#assign classImports = []>
<#list selectContext.columns as column>
    <#if !column.type.javaClass.name?starts_with("java.lang.") && !column.type.javaClass.name?contains("[") && !classImports?seq_contains(column.type.javaClass.name)>
        <#assign classImports = classImports + [column.type.javaClass.name]>
import ${column.type.javaClass.name};
    </#if>
</#list>
import java.util.Objects;

/**
 * Query result class for statement ${statementDeclaration.name}.
 * <p>
 * Generated by SQLComments.
 */
public class ${simpleClassName} <#if interfaces?has_content>implements ${interfaces} </#if>{

<#list selectContext.columns as column>
    private ${column.type.javaClass.simpleName} ${column.javaIdentifier};
</#list>

<#list selectContext.columns as column>
    public ${column.type.javaClass.simpleName} get${column.javaIdentifier[0]?upper_case}${column.javaIdentifier[1..]}() {
        return ${column.javaIdentifier};
    }

    public void set${column.javaIdentifier[0]?upper_case}${column.javaIdentifier[1..]}(${column.type.javaClass.simpleName} newValue) {
        this.${column.javaIdentifier} = newValue;
    }

</#list>
    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("${simpleClassName} [${selectContext.columns[0].javaIdentifier}=");
        builder.append(${selectContext.columns[0].javaIdentifier});
    <#list selectContext.columns[1..] as column>
        builder.append(", ${column.javaIdentifier}=");
        builder.append(${column.javaIdentifier});
    </#list>
        builder.append("]");
        return builder.toString();
    }
    
<#if primaryKeys??>
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        ${simpleClassName} other = (${simpleClassName}) obj;
        <#list primaryKeys as key>
            <#list selectContext.columns as column><#if column.columnName = key>
        if (!Objects.equals(${column.javaIdentifier}, other.${column.javaIdentifier})) return false;
            </#if></#list>
        </#list>
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        <#list primaryKeys as key>
            <#list selectContext.columns as column><#if column.columnName = key>
        result = prime * result + ((${column.javaIdentifier} == null) ? 0 : ${column.javaIdentifier}.hashCode());
            </#if></#list>
        </#list>
        return result;
    }
</#if>
}