package sk.vracon.sqlcomments.maven.domain.MariaDB;

import java.util.Date;
import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Datatypes {

    private Long bigInt;
    private byte[] binary;
    private byte[] bit;
    private Boolean bool;
    private Boolean boolean_;
    private String char_;
    private Date date;
    private Date dateTime;
    private BigDecimal dec;
    private BigDecimal decimal;
    private Double doublePrecision;
    private Double double_;
    private String enum_;
    private BigDecimal fixed;
    private Float float_;
    private byte[] geometry;
    private byte[] geometryCollection;
    private Integer int_;
    private byte[] lineString;
    private Blob longBlob;
    private String longText;
    private Blob mediumBlob;
    private Integer mediumInt;
    private String mediumText;
    private byte[] multiLineString;
    private byte[] multiPoint;
    private byte[] multiPolygon;
    private String nChar;
    private String nVarChar;
    private String nationalChar;
    private String nationalVarchar;
    private BigDecimal numeric;
    private byte[] point;
    private byte[] polygon;
    private Double real;
    private String set;
    private Integer smallInt;
    private String text;
    private Date time;
    private Date timeStamp;
    private byte[] tinyBlob;
    private Integer tinyInt;
    private String tinyText;
    private byte[] varBinary;
    private String varChar;
    private Date year4;

    public Long getBigInt() {
        return bigInt;
    }

    public void setBigInt(Long newValue) {
        this.bigInt = newValue;
    }

    public byte[] getBinary() {
        return binary;
    }

    public void setBinary(byte[] newValue) {
        this.binary = newValue;
    }

    public byte[] getBit() {
        return bit;
    }

    public void setBit(byte[] newValue) {
        this.bit = newValue;
    }

    public Boolean getBool() {
        return bool;
    }

    public void setBool(Boolean newValue) {
        this.bool = newValue;
    }

    public Boolean getBoolean_() {
        return boolean_;
    }

    public void setBoolean_(Boolean newValue) {
        this.boolean_ = newValue;
    }

    public String getChar_() {
        return char_;
    }

    public void setChar_(String newValue) {
        this.char_ = newValue;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date newValue) {
        this.date = newValue;
    }

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date newValue) {
        this.dateTime = newValue;
    }

    public BigDecimal getDec() {
        return dec;
    }

    public void setDec(BigDecimal newValue) {
        this.dec = newValue;
    }

    public BigDecimal getDecimal() {
        return decimal;
    }

    public void setDecimal(BigDecimal newValue) {
        this.decimal = newValue;
    }

    public Double getDoublePrecision() {
        return doublePrecision;
    }

    public void setDoublePrecision(Double newValue) {
        this.doublePrecision = newValue;
    }

    public Double getDouble_() {
        return double_;
    }

    public void setDouble_(Double newValue) {
        this.double_ = newValue;
    }

    public String getEnum_() {
        return enum_;
    }

    public void setEnum_(String newValue) {
        this.enum_ = newValue;
    }

    public BigDecimal getFixed() {
        return fixed;
    }

    public void setFixed(BigDecimal newValue) {
        this.fixed = newValue;
    }

    public Float getFloat_() {
        return float_;
    }

    public void setFloat_(Float newValue) {
        this.float_ = newValue;
    }

    public byte[] getGeometry() {
        return geometry;
    }

    public void setGeometry(byte[] newValue) {
        this.geometry = newValue;
    }

    public byte[] getGeometryCollection() {
        return geometryCollection;
    }

    public void setGeometryCollection(byte[] newValue) {
        this.geometryCollection = newValue;
    }

    public Integer getInt_() {
        return int_;
    }

    public void setInt_(Integer newValue) {
        this.int_ = newValue;
    }

    public byte[] getLineString() {
        return lineString;
    }

    public void setLineString(byte[] newValue) {
        this.lineString = newValue;
    }

    public Blob getLongBlob() {
        return longBlob;
    }

    public void setLongBlob(Blob newValue) {
        this.longBlob = newValue;
    }

    public String getLongText() {
        return longText;
    }

    public void setLongText(String newValue) {
        this.longText = newValue;
    }

    public Blob getMediumBlob() {
        return mediumBlob;
    }

    public void setMediumBlob(Blob newValue) {
        this.mediumBlob = newValue;
    }

    public Integer getMediumInt() {
        return mediumInt;
    }

    public void setMediumInt(Integer newValue) {
        this.mediumInt = newValue;
    }

    public String getMediumText() {
        return mediumText;
    }

    public void setMediumText(String newValue) {
        this.mediumText = newValue;
    }

    public byte[] getMultiLineString() {
        return multiLineString;
    }

    public void setMultiLineString(byte[] newValue) {
        this.multiLineString = newValue;
    }

    public byte[] getMultiPoint() {
        return multiPoint;
    }

    public void setMultiPoint(byte[] newValue) {
        this.multiPoint = newValue;
    }

    public byte[] getMultiPolygon() {
        return multiPolygon;
    }

    public void setMultiPolygon(byte[] newValue) {
        this.multiPolygon = newValue;
    }

    public String getNChar() {
        return nChar;
    }

    public void setNChar(String newValue) {
        this.nChar = newValue;
    }

    public String getNVarChar() {
        return nVarChar;
    }

    public void setNVarChar(String newValue) {
        this.nVarChar = newValue;
    }

    public String getNationalChar() {
        return nationalChar;
    }

    public void setNationalChar(String newValue) {
        this.nationalChar = newValue;
    }

    public String getNationalVarchar() {
        return nationalVarchar;
    }

    public void setNationalVarchar(String newValue) {
        this.nationalVarchar = newValue;
    }

    public BigDecimal getNumeric() {
        return numeric;
    }

    public void setNumeric(BigDecimal newValue) {
        this.numeric = newValue;
    }

    public byte[] getPoint() {
        return point;
    }

    public void setPoint(byte[] newValue) {
        this.point = newValue;
    }

    public byte[] getPolygon() {
        return polygon;
    }

    public void setPolygon(byte[] newValue) {
        this.polygon = newValue;
    }

    public Double getReal() {
        return real;
    }

    public void setReal(Double newValue) {
        this.real = newValue;
    }

    public String getSet() {
        return set;
    }

    public void setSet(String newValue) {
        this.set = newValue;
    }

    public Integer getSmallInt() {
        return smallInt;
    }

    public void setSmallInt(Integer newValue) {
        this.smallInt = newValue;
    }

    public String getText() {
        return text;
    }

    public void setText(String newValue) {
        this.text = newValue;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date newValue) {
        this.time = newValue;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date newValue) {
        this.timeStamp = newValue;
    }

    public byte[] getTinyBlob() {
        return tinyBlob;
    }

    public void setTinyBlob(byte[] newValue) {
        this.tinyBlob = newValue;
    }

    public Integer getTinyInt() {
        return tinyInt;
    }

    public void setTinyInt(Integer newValue) {
        this.tinyInt = newValue;
    }

    public String getTinyText() {
        return tinyText;
    }

    public void setTinyText(String newValue) {
        this.tinyText = newValue;
    }

    public byte[] getVarBinary() {
        return varBinary;
    }

    public void setVarBinary(byte[] newValue) {
        this.varBinary = newValue;
    }

    public String getVarChar() {
        return varChar;
    }

    public void setVarChar(String newValue) {
        this.varChar = newValue;
    }

    public Date getYear4() {
        return year4;
    }

    public void setYear4(Date newValue) {
        this.year4 = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Datatypes [bigInt=");
        builder.append(bigInt);
        builder.append(", binary=");
        builder.append(binary);
        builder.append(", bit=");
        builder.append(bit);
        builder.append(", bool=");
        builder.append(bool);
        builder.append(", boolean_=");
        builder.append(boolean_);
        builder.append(", char_=");
        builder.append(char_);
        builder.append(", date=");
        builder.append(date);
        builder.append(", dateTime=");
        builder.append(dateTime);
        builder.append(", dec=");
        builder.append(dec);
        builder.append(", decimal=");
        builder.append(decimal);
        builder.append(", doublePrecision=");
        builder.append(doublePrecision);
        builder.append(", double_=");
        builder.append(double_);
        builder.append(", enum_=");
        builder.append(enum_);
        builder.append(", fixed=");
        builder.append(fixed);
        builder.append(", float_=");
        builder.append(float_);
        builder.append(", geometry=");
        builder.append(geometry);
        builder.append(", geometryCollection=");
        builder.append(geometryCollection);
        builder.append(", int_=");
        builder.append(int_);
        builder.append(", lineString=");
        builder.append(lineString);
        builder.append(", longBlob=");
        builder.append(longBlob);
        builder.append(", longText=");
        builder.append(longText);
        builder.append(", mediumBlob=");
        builder.append(mediumBlob);
        builder.append(", mediumInt=");
        builder.append(mediumInt);
        builder.append(", mediumText=");
        builder.append(mediumText);
        builder.append(", multiLineString=");
        builder.append(multiLineString);
        builder.append(", multiPoint=");
        builder.append(multiPoint);
        builder.append(", multiPolygon=");
        builder.append(multiPolygon);
        builder.append(", nChar=");
        builder.append(nChar);
        builder.append(", nVarChar=");
        builder.append(nVarChar);
        builder.append(", nationalChar=");
        builder.append(nationalChar);
        builder.append(", nationalVarchar=");
        builder.append(nationalVarchar);
        builder.append(", numeric=");
        builder.append(numeric);
        builder.append(", point=");
        builder.append(point);
        builder.append(", polygon=");
        builder.append(polygon);
        builder.append(", real=");
        builder.append(real);
        builder.append(", set=");
        builder.append(set);
        builder.append(", smallInt=");
        builder.append(smallInt);
        builder.append(", text=");
        builder.append(text);
        builder.append(", time=");
        builder.append(time);
        builder.append(", timeStamp=");
        builder.append(timeStamp);
        builder.append(", tinyBlob=");
        builder.append(tinyBlob);
        builder.append(", tinyInt=");
        builder.append(tinyInt);
        builder.append(", tinyText=");
        builder.append(tinyText);
        builder.append(", varBinary=");
        builder.append(varBinary);
        builder.append(", varChar=");
        builder.append(varChar);
        builder.append(", year4=");
        builder.append(year4);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Datatypes other = (Datatypes) obj;
        if (!Objects.equals(int_, other.int_)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((int_ == null) ? 0 : int_.hashCode());
        return result;
    }
}