package sk.vracon.sqlcomments.maven.domain.MariaDB;

import sk.vracon.sqlcomments.maven.DepartmenTypesEnum;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Dept {

    private Integer deptno;
    private DepartmenTypesEnum dname;
    private String loc;

    public Integer getDeptno() {
        return deptno;
    }

    public void setDeptno(Integer newValue) {
        this.deptno = newValue;
    }

    public DepartmenTypesEnum getDname() {
        return dname;
    }

    public void setDname(DepartmenTypesEnum newValue) {
        this.dname = newValue;
    }

    public String getLoc() {
        return loc;
    }

    public void setLoc(String newValue) {
        this.loc = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Dept [deptno=");
        builder.append(deptno);
        builder.append(", dname=");
        builder.append(dname);
        builder.append(", loc=");
        builder.append(loc);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Dept other = (Dept) obj;
        if (!Objects.equals(deptno, other.deptno)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((deptno == null) ? 0 : deptno.hashCode());
        return result;
    }
}