package sk.vracon.sqlcomments.maven.domain.MariaDB;

import java.util.Objects;

/**
 * Query result class for statement selectAll.
 * <p>
 * Generated by SQLComments.
 */
public class Managers {

    private String employee;
    private String manager;

    public String getEmployee() {
        return employee;
    }

    public void setEmployee(String newValue) {
        this.employee = newValue;
    }

    public String getManager() {
        return manager;
    }

    public void setManager(String newValue) {
        this.manager = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Managers [employee=");
        builder.append(employee);
        builder.append(", manager=");
        builder.append(manager);
        builder.append("]");
        return builder.toString();
    }
    
}