

create table companies (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50),
	city VARCHAR(50),
	email VARCHAR(50),
	country VARCHAR(50),
	ip_address VARCHAR(20)
);


create table users (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	country VARCHAR(50),
	companyId INT
);

create table documents (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50),
	description VARCHAR(500),
	userId INT,
	data BLOB,
	FOREIGN KEY (id) REFERENCES companies(id)
);
