package sk.vracon.sqlcomments.maven.domain.PostgreSQL;

import java.sql.Array;
import java.util.Date;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Datatypes {

    private Long bigInt;
    private byte[] bit;
    private byte[] bitVarying;
    private byte[] bool;
    private byte[] boolean_;
    private byte[] box;
    private byte[] bytea;
    private Array charArray;
    private String char_;
    private String character;
    private String characterVarying;
    private byte[] cid;
    private byte[] cidr;
    private byte[] circle;
    private Date date;
    private BigDecimal decimal;
    private Double doublePrecision;
    private String enum_;
    private Float float4;
    private Double float8;
    private byte[] inet;
    private Integer int2;
    private Integer int4;
    private Long int8;
    private Array intArray;
    private Integer int_;
    private Integer integer;
    private byte[] interval;
    private byte[] line;
    private byte[] lseg;
    private byte[] macaddr;
    private Double money;
    private BigDecimal numeric;
    private Long oid;
    private byte[] path;
    private byte[] point;
    private byte[] polygon;
    private Float real;
    private byte[] regClass;
    private byte[] regOper;
    private byte[] regOperator;
    private byte[] regProc;
    private byte[] regProcedure;
    private byte[] regType;
    private Integer smallInt;
    private String text;
    private Date time;
    private Date timeTz;
    private Date timeWotz;
    private Date timeWtz;
    private Date timestamp;
    private Date timestampTz;
    private Date timestampWtz;
    private byte[] tsQuery;
    private byte[] tsVector;
    private byte[] txidSnapshot;
    private byte[] uuid;
    private byte[] varBit;
    private String varchar;
    private Array varcharArray;
    private String xml;

    public Long getBigInt() {
        return bigInt;
    }

    public void setBigInt(Long newValue) {
        this.bigInt = newValue;
    }

    public byte[] getBit() {
        return bit;
    }

    public void setBit(byte[] newValue) {
        this.bit = newValue;
    }

    public byte[] getBitVarying() {
        return bitVarying;
    }

    public void setBitVarying(byte[] newValue) {
        this.bitVarying = newValue;
    }

    public byte[] getBool() {
        return bool;
    }

    public void setBool(byte[] newValue) {
        this.bool = newValue;
    }

    public byte[] getBoolean_() {
        return boolean_;
    }

    public void setBoolean_(byte[] newValue) {
        this.boolean_ = newValue;
    }

    public byte[] getBox() {
        return box;
    }

    public void setBox(byte[] newValue) {
        this.box = newValue;
    }

    public byte[] getBytea() {
        return bytea;
    }

    public void setBytea(byte[] newValue) {
        this.bytea = newValue;
    }

    public Array getCharArray() {
        return charArray;
    }

    public void setCharArray(Array newValue) {
        this.charArray = newValue;
    }

    public String getChar_() {
        return char_;
    }

    public void setChar_(String newValue) {
        this.char_ = newValue;
    }

    public String getCharacter() {
        return character;
    }

    public void setCharacter(String newValue) {
        this.character = newValue;
    }

    public String getCharacterVarying() {
        return characterVarying;
    }

    public void setCharacterVarying(String newValue) {
        this.characterVarying = newValue;
    }

    public byte[] getCid() {
        return cid;
    }

    public void setCid(byte[] newValue) {
        this.cid = newValue;
    }

    public byte[] getCidr() {
        return cidr;
    }

    public void setCidr(byte[] newValue) {
        this.cidr = newValue;
    }

    public byte[] getCircle() {
        return circle;
    }

    public void setCircle(byte[] newValue) {
        this.circle = newValue;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date newValue) {
        this.date = newValue;
    }

    public BigDecimal getDecimal() {
        return decimal;
    }

    public void setDecimal(BigDecimal newValue) {
        this.decimal = newValue;
    }

    public Double getDoublePrecision() {
        return doublePrecision;
    }

    public void setDoublePrecision(Double newValue) {
        this.doublePrecision = newValue;
    }

    public String getEnum_() {
        return enum_;
    }

    public void setEnum_(String newValue) {
        this.enum_ = newValue;
    }

    public Float getFloat4() {
        return float4;
    }

    public void setFloat4(Float newValue) {
        this.float4 = newValue;
    }

    public Double getFloat8() {
        return float8;
    }

    public void setFloat8(Double newValue) {
        this.float8 = newValue;
    }

    public byte[] getInet() {
        return inet;
    }

    public void setInet(byte[] newValue) {
        this.inet = newValue;
    }

    public Integer getInt2() {
        return int2;
    }

    public void setInt2(Integer newValue) {
        this.int2 = newValue;
    }

    public Integer getInt4() {
        return int4;
    }

    public void setInt4(Integer newValue) {
        this.int4 = newValue;
    }

    public Long getInt8() {
        return int8;
    }

    public void setInt8(Long newValue) {
        this.int8 = newValue;
    }

    public Array getIntArray() {
        return intArray;
    }

    public void setIntArray(Array newValue) {
        this.intArray = newValue;
    }

    public Integer getInt_() {
        return int_;
    }

    public void setInt_(Integer newValue) {
        this.int_ = newValue;
    }

    public Integer getInteger() {
        return integer;
    }

    public void setInteger(Integer newValue) {
        this.integer = newValue;
    }

    public byte[] getInterval() {
        return interval;
    }

    public void setInterval(byte[] newValue) {
        this.interval = newValue;
    }

    public byte[] getLine() {
        return line;
    }

    public void setLine(byte[] newValue) {
        this.line = newValue;
    }

    public byte[] getLseg() {
        return lseg;
    }

    public void setLseg(byte[] newValue) {
        this.lseg = newValue;
    }

    public byte[] getMacaddr() {
        return macaddr;
    }

    public void setMacaddr(byte[] newValue) {
        this.macaddr = newValue;
    }

    public Double getMoney() {
        return money;
    }

    public void setMoney(Double newValue) {
        this.money = newValue;
    }

    public BigDecimal getNumeric() {
        return numeric;
    }

    public void setNumeric(BigDecimal newValue) {
        this.numeric = newValue;
    }

    public Long getOid() {
        return oid;
    }

    public void setOid(Long newValue) {
        this.oid = newValue;
    }

    public byte[] getPath() {
        return path;
    }

    public void setPath(byte[] newValue) {
        this.path = newValue;
    }

    public byte[] getPoint() {
        return point;
    }

    public void setPoint(byte[] newValue) {
        this.point = newValue;
    }

    public byte[] getPolygon() {
        return polygon;
    }

    public void setPolygon(byte[] newValue) {
        this.polygon = newValue;
    }

    public Float getReal() {
        return real;
    }

    public void setReal(Float newValue) {
        this.real = newValue;
    }

    public byte[] getRegClass() {
        return regClass;
    }

    public void setRegClass(byte[] newValue) {
        this.regClass = newValue;
    }

    public byte[] getRegOper() {
        return regOper;
    }

    public void setRegOper(byte[] newValue) {
        this.regOper = newValue;
    }

    public byte[] getRegOperator() {
        return regOperator;
    }

    public void setRegOperator(byte[] newValue) {
        this.regOperator = newValue;
    }

    public byte[] getRegProc() {
        return regProc;
    }

    public void setRegProc(byte[] newValue) {
        this.regProc = newValue;
    }

    public byte[] getRegProcedure() {
        return regProcedure;
    }

    public void setRegProcedure(byte[] newValue) {
        this.regProcedure = newValue;
    }

    public byte[] getRegType() {
        return regType;
    }

    public void setRegType(byte[] newValue) {
        this.regType = newValue;
    }

    public Integer getSmallInt() {
        return smallInt;
    }

    public void setSmallInt(Integer newValue) {
        this.smallInt = newValue;
    }

    public String getText() {
        return text;
    }

    public void setText(String newValue) {
        this.text = newValue;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date newValue) {
        this.time = newValue;
    }

    public Date getTimeTz() {
        return timeTz;
    }

    public void setTimeTz(Date newValue) {
        this.timeTz = newValue;
    }

    public Date getTimeWotz() {
        return timeWotz;
    }

    public void setTimeWotz(Date newValue) {
        this.timeWotz = newValue;
    }

    public Date getTimeWtz() {
        return timeWtz;
    }

    public void setTimeWtz(Date newValue) {
        this.timeWtz = newValue;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date newValue) {
        this.timestamp = newValue;
    }

    public Date getTimestampTz() {
        return timestampTz;
    }

    public void setTimestampTz(Date newValue) {
        this.timestampTz = newValue;
    }

    public Date getTimestampWtz() {
        return timestampWtz;
    }

    public void setTimestampWtz(Date newValue) {
        this.timestampWtz = newValue;
    }

    public byte[] getTsQuery() {
        return tsQuery;
    }

    public void setTsQuery(byte[] newValue) {
        this.tsQuery = newValue;
    }

    public byte[] getTsVector() {
        return tsVector;
    }

    public void setTsVector(byte[] newValue) {
        this.tsVector = newValue;
    }

    public byte[] getTxidSnapshot() {
        return txidSnapshot;
    }

    public void setTxidSnapshot(byte[] newValue) {
        this.txidSnapshot = newValue;
    }

    public byte[] getUuid() {
        return uuid;
    }

    public void setUuid(byte[] newValue) {
        this.uuid = newValue;
    }

    public byte[] getVarBit() {
        return varBit;
    }

    public void setVarBit(byte[] newValue) {
        this.varBit = newValue;
    }

    public String getVarchar() {
        return varchar;
    }

    public void setVarchar(String newValue) {
        this.varchar = newValue;
    }

    public Array getVarcharArray() {
        return varcharArray;
    }

    public void setVarcharArray(Array newValue) {
        this.varcharArray = newValue;
    }

    public String getXml() {
        return xml;
    }

    public void setXml(String newValue) {
        this.xml = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Datatypes [bigInt=");
        builder.append(bigInt);
        builder.append(", bit=");
        builder.append(bit);
        builder.append(", bitVarying=");
        builder.append(bitVarying);
        builder.append(", bool=");
        builder.append(bool);
        builder.append(", boolean_=");
        builder.append(boolean_);
        builder.append(", box=");
        builder.append(box);
        builder.append(", bytea=");
        builder.append(bytea);
        builder.append(", charArray=");
        builder.append(charArray);
        builder.append(", char_=");
        builder.append(char_);
        builder.append(", character=");
        builder.append(character);
        builder.append(", characterVarying=");
        builder.append(characterVarying);
        builder.append(", cid=");
        builder.append(cid);
        builder.append(", cidr=");
        builder.append(cidr);
        builder.append(", circle=");
        builder.append(circle);
        builder.append(", date=");
        builder.append(date);
        builder.append(", decimal=");
        builder.append(decimal);
        builder.append(", doublePrecision=");
        builder.append(doublePrecision);
        builder.append(", enum_=");
        builder.append(enum_);
        builder.append(", float4=");
        builder.append(float4);
        builder.append(", float8=");
        builder.append(float8);
        builder.append(", inet=");
        builder.append(inet);
        builder.append(", int2=");
        builder.append(int2);
        builder.append(", int4=");
        builder.append(int4);
        builder.append(", int8=");
        builder.append(int8);
        builder.append(", intArray=");
        builder.append(intArray);
        builder.append(", int_=");
        builder.append(int_);
        builder.append(", integer=");
        builder.append(integer);
        builder.append(", interval=");
        builder.append(interval);
        builder.append(", line=");
        builder.append(line);
        builder.append(", lseg=");
        builder.append(lseg);
        builder.append(", macaddr=");
        builder.append(macaddr);
        builder.append(", money=");
        builder.append(money);
        builder.append(", numeric=");
        builder.append(numeric);
        builder.append(", oid=");
        builder.append(oid);
        builder.append(", path=");
        builder.append(path);
        builder.append(", point=");
        builder.append(point);
        builder.append(", polygon=");
        builder.append(polygon);
        builder.append(", real=");
        builder.append(real);
        builder.append(", regClass=");
        builder.append(regClass);
        builder.append(", regOper=");
        builder.append(regOper);
        builder.append(", regOperator=");
        builder.append(regOperator);
        builder.append(", regProc=");
        builder.append(regProc);
        builder.append(", regProcedure=");
        builder.append(regProcedure);
        builder.append(", regType=");
        builder.append(regType);
        builder.append(", smallInt=");
        builder.append(smallInt);
        builder.append(", text=");
        builder.append(text);
        builder.append(", time=");
        builder.append(time);
        builder.append(", timeTz=");
        builder.append(timeTz);
        builder.append(", timeWotz=");
        builder.append(timeWotz);
        builder.append(", timeWtz=");
        builder.append(timeWtz);
        builder.append(", timestamp=");
        builder.append(timestamp);
        builder.append(", timestampTz=");
        builder.append(timestampTz);
        builder.append(", timestampWtz=");
        builder.append(timestampWtz);
        builder.append(", tsQuery=");
        builder.append(tsQuery);
        builder.append(", tsVector=");
        builder.append(tsVector);
        builder.append(", txidSnapshot=");
        builder.append(txidSnapshot);
        builder.append(", uuid=");
        builder.append(uuid);
        builder.append(", varBit=");
        builder.append(varBit);
        builder.append(", varchar=");
        builder.append(varchar);
        builder.append(", varcharArray=");
        builder.append(varcharArray);
        builder.append(", xml=");
        builder.append(xml);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Datatypes other = (Datatypes) obj;
        if (!Objects.equals(integer, other.integer)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((integer == null) ? 0 : integer.hashCode());
        return result;
    }
}