package sk.vracon.sqlcomments.maven.domain.PostgreSQL;

import java.util.Date;
import java.util.Objects;

/**
 * Query result class for statement findByPK.
 * <p>
 * Generated by SQLComments.
 */
public class Emp {

    private Integer comm;
    private Integer deptno;
    private Integer empno;
    private String ename;
    private Date hiredate;
    private String job;
    private Integer mgr;
    private Integer sal;

    public Integer getComm() {
        return comm;
    }

    public void setComm(Integer newValue) {
        this.comm = newValue;
    }

    public Integer getDeptno() {
        return deptno;
    }

    public void setDeptno(Integer newValue) {
        this.deptno = newValue;
    }

    public Integer getEmpno() {
        return empno;
    }

    public void setEmpno(Integer newValue) {
        this.empno = newValue;
    }

    public String getEname() {
        return ename;
    }

    public void setEname(String newValue) {
        this.ename = newValue;
    }

    public Date getHiredate() {
        return hiredate;
    }

    public void setHiredate(Date newValue) {
        this.hiredate = newValue;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String newValue) {
        this.job = newValue;
    }

    public Integer getMgr() {
        return mgr;
    }

    public void setMgr(Integer newValue) {
        this.mgr = newValue;
    }

    public Integer getSal() {
        return sal;
    }

    public void setSal(Integer newValue) {
        this.sal = newValue;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Emp [comm=");
        builder.append(comm);
        builder.append(", deptno=");
        builder.append(deptno);
        builder.append(", empno=");
        builder.append(empno);
        builder.append(", ename=");
        builder.append(ename);
        builder.append(", hiredate=");
        builder.append(hiredate);
        builder.append(", job=");
        builder.append(job);
        builder.append(", mgr=");
        builder.append(mgr);
        builder.append(", sal=");
        builder.append(sal);
        builder.append("]");
        return builder.toString();
    }
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Emp other = (Emp) obj;
        if (!Objects.equals(empno, other.empno)) return false;
        return true;
    }    
    
    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((empno == null) ? 0 : empno.hashCode());
        return result;
    }
}