/*
 * Copyright 2014 Vracon s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sk.vracon.sqlcomments.core;

import java.sql.PreparedStatement;
import java.sql.Types;
import java.util.Map;
import java.util.Set;

/**
 * Basic interface representing statement configuration.
 * <p>
 * Statement configuration means mainly its name and parameters controlling creation of SQL string.
 */
public interface StatementConfiguration extends SQLCommentsConfiguration {

    /**
     * Returns statement name.
     * <p>
     * Statement name can be represented in two ways:
     * <ol>
     * <li>{@link #baseClass()} returns null - name must be full path to sql file including file extension.</li>
     * <li>{@link #baseClass()} returns real class - name is just a part of path. Full name (and full path) is
     * concatenation of base classes' path this name and .sql extension.</li>
     * </ol>
     * <p>
     * Statement name may not be null.
     * 
     * @return statement name.
     * 
     * @see #baseClass()
     */
    public String statementName();

    /**
     * Returns base class.
     * <p>
     * Base class has two functions:
     * <ol>
     * <li>Class name is used as a prefix of statement file name.</li>
     * <li>Class loader of this class is used also to load statement file.</li>
     * </ol>
     * <p>
     * Statements generated from java comments use as a base class the same class from which they were extracted.
     * 
     * @return base class or null
     * 
     * @see #statementName()
     */
    public Class<?> baseClass();

    /**
     * Map of parameters to construct statement in runtime.
     * <p>
     * Map contains parameters which can be used as each of three possibilities:
     * <ul>
     * <li>SQL parameter</li>
     * <li>Script parameter</li>
     * <li>Replacement</li>
     * </ul>
     * <p>
     * In runtime if parameter is used as a SQL parameter and has null value or is missing at all - it means to skip
     * statement row. Exception to this rule are parameters returned by {@link #parametersAcceptingNull()}.
     * 
     * @return parameters to construct statement
     * 
     * @see #parametersAcceptingNull()
     */
    public Map<String, Object> parameterMap();

    /**
     * Map of parameter names and {@link Types}s.
     * <p>
     * This mapping between parameters and their types is used to read and write values to {@link PreparedStatement}.
     * {@link Type#writeValue(PreparedStatement, int, Object)} is used to convert and set values to statement.
     * {@link Type#readValue(java.sql.ResultSet, String)} is used to read generated key values if needed.
     * 
     * @return a map of parameter names and {@link Types}s
     */
    public Map<String, Type<?>> typeMap();

    /**
     * Returns parameters for which null doesn't mean to skip row.
     * <p>
     * This is useful mainly in Insert statements, rarely otherwise.
     * 
     * @return parameters for which null doesn't mean to skip row
     * 
     * @see #parameterMap()
     */
    public Set<String> parametersAcceptingNull();

    /**
     * Returns column names defined as a primary key.
     * <p>
     * This method is used in conjunction with insert statements where primary key values are generated by database.  
     * 
     * @return a list of column names defined as generated primary key.
     */
    public Set<String> primaryKey();
    
    /**
     * Gets maximum number of rows to be loaded.
     * 
     * @return limit
     */
    public Long limit();

    /**
     * Sets maximum number of rows to be loaded.
     * 
     * @param limit
     *            limit
     */
    public void limit(Long limit);

    /**
     * Gets result set offset.
     * 
     * @return offset
     */
    public Long offset();

    /**
     * Sets result set offset.
     * 
     * @param offset
     *            offset
     */
    public void offset(Long offset);
}
